spring:  
  application:
    name: discovery-service
    
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:  
  port: ${PORT:8761}

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
server:  
  port: ${PORT:8762}
  
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:  
  port: ${PORT:8763}