spring:  
  application:
    name: customer-service

server:  
  port: ${PORT:8092}
  ssl:
    enabled: true
    key-store: classpath:customer.jks
    key-store-password: 123456
    key-alias: customer
    
security:
  require-ssl: true
  
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${PORT:8092}
    statusPageUrl: https://localhost:${eureka.instance.securePort}/info
    healthCheckUrl: https://localhost:${eureka.instance.securePort}/health
    homePageUrl: https://localhost:${eureka.instance.securePort}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
